services:
  db:
    image: postgres:16
    platform: linux/amd64
    environment:
      POSTGRES_USER: Bar-Buddy_postgres_user
      POSTGRES_PASSWORD: Bar-Buddy_postgres_password
      POSTGRES_DB: Bar-Buddy_development
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && rm -rf tmp/cache && rm -f tmp/sockets/* && bundle exec rails s -b '0.0.0.0'"
    volumes:
      - ".:/app"
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      POSTGRES_USER: Bar-Buddy_postgres_user
      POSTGRES_PASSWORD: Bar-Buddy_postgres_password
      POSTGRES_DB: Bar-Buddy_development
      DATABASE_URL: postgres://Bar-Buddy_postgres_user:Bar-Buddy_postgres_password@db/Bar-Buddy_development

volumes:
  postgres-data: